name: Ubuntu x86
on: workflow_dispatch
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: curl -O "https://download.java.net/java/early_access/jextract/22/5/openjdk-22-jextract+5-33_linux-x64_bin.tar.gz"
      - shell: bash
        run: tar -xzvf openjdk-22-jextract+5-33_linux-x64_bin.tar.gz
      - shell: bash
        run: chmod +x jextract-22/bin/jextract && ./src/gen/shell/linux_amd64.sh
      - shell: bash
        run: rm -rf openjdk-22-jextract+5-33_linux-x64_bin.tar.gz && rm -rf jextract-22
      - uses: stefanzweifel/git-auto-commit-action@v4
