name: MacOS ARM
on: workflow_dispatch
jobs:
  generate:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "23"
          distribution: "adopt"
      - run: curl -s "https://get.sdkman.io" | bash
      - run: source "/Users/runner/.sdkman/bin/sdkman-init.sh" && sdk install jextract 22.ea.5 && chmod +x mac_arm.sh && ./mac_arm.sh
