name: MacOS ARM
on: workflow_dispatch
jobs:
  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: curl -s "https://get.sdkman.io" | bash
      - run: source "/Users/runner/.sdkman/bin/sdkman-init.sh" && sdk install jextract 22.ea.5 && chmod +x src/gen/shell/mac_arm.sh && ./src/gen/shell/mac_arm.sh
      - uses: stefanzweifel/git-auto-commit-action@v4