name: Windows x86
on: workflow_dispatch
jobs:
  generate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: curl -O "https://download.java.net/java/early_access/jextract/22/5/openjdk-22-jextract+5-33_windows-x64_bin.tar.gz"
      - shell: bash
        run: ls
      - shell: bash
        run: tar -xzvf openjdk-22-jextract+5-33_windows-x64_bin.tar.gz
      - shell: bash
        run: ls
      - shell: bash
        run: chmod +x jextract-22/bin/jextract && ./windows_x86.sh
      
